### ISSUE TITLE
How to set it as a New Tab?

### ISSUE THREAD

**Issue by dhruvnnd** [Ozencb/tilde-enhanced#14]
**Firefox** is not allowing to set custom URLs as New Tab. So, is there any way I can set it as my new tab?

**Comment by ozencb** [comment]
Check the last section of README

**Comment by dhruvnnd** [comment]
I visited the same [link](https://github.com/Urimu/Startpage#setting-it-up-on-firefox) as mentioned in the **README** but it doesn't seem to be working. 
This is the reason I have created this Issue. 

![Page Not Found](https://user-images.githubusercontent.com/65074550/130892032-b4c67d73-78e6-46b5-9ea7-574c4a3254e2.png)

**Comment by ozencb** [comment]
Oh, I see. I will try to find out if that method still works then write an instruction myself. Meanwhile, I'll copy & paste the instruction from the broken link:

- Go to "about:preferences#home" (Options in top right menu > home), set "Homepage and new windows" to Custom URLs and enter "file:///path/to/the/index.html"

- Set "New tabs" to "Blank Page" then go to the installation folder of Firefox, "C:\Program Files\Mozilla Firefox" is default on Windows, open "defaults" then "pref" and put the "autoconfig.js" (from "Firefox_cfg") there. Go back to the installation folder and paste "autoconfig.cfg" (from "Firefox_cfg") in, open it and edit the "newTabURL" to the file path of the index.html

**Comment by dhruvnnd** [comment]
I have created a **Gist** with the given instructions, I hope it is helpful. 

[Gist Link](https://gist.github.com/iDCoded/f8a67767e96b8675a8a77ea7fb406211)

**Comment by ozencb** [comment]
Thanks a lot! If this method still works I can merge if you want to update the README and do a PR
