### ISSUE TITLE
New icon for mastodon

### ISSUE THREAD

**Issue by jakiisheep** [Ozencb/tilde-enhanced#15]
Hello! I love this project and I use it for my startpage. However, I wan't to replace the LinkedIn icon with the Mastodon icon but I can't seem to make the mastodon icon in photoshop, if you could make one, it would be amazing.

This is linked to #1

**Comment by ozencb** [comment]
Hello, thank you for the feedback! 
I am afraid I don't have the time to make new icons. You can use the existing ones as reference
