### ISSUE TITLE
New Page

### ISSUE THREAD

**Issue by ankytastic** [Ozencb/tilde-enhanced#16]
I want to make such changes in the code in such a way that whenever any new link is opened it should be opened in the new page,rather than in the same page and the home page comes back to clock face.

**Comment by ozencb** [comment]
Set `newTab` to `true` on `config.js` 

https://github.com/Ozencb/tilde-enhanced/blob/23ab5223d022b21ac1b81d37a9c6194ab0de612b/js/config.js#LL266C2-L266C2
