### ISSUE TITLE
12 Hour - AM/PM

### ISSUE THREAD

**Issue by travisjneuman** [Ozencb/tilde-enhanced#3]
Hey @Ozencb , love the /r/startpage you have created here.

I have ended up building a website using this repo of yours, and it is now my standard homepage.

I did want to share that I have noticed one issue with the AM/PM switch-over around noon (and perhaps midnight, but I have not paid attention to it at that time of day).
 - Pictures are attached, explanation of what I have noticed is below.

![12 Afternoon AM](https://user-images.githubusercontent.com/33078474/59291704-72eac300-8c49-11e9-8e35-3e38e120b30b.png)
![1 Afternoon PM](https://user-images.githubusercontent.com/33078474/59291709-75e5b380-8c49-11e9-9a0a-dcba9d1522eb.png)

So essentially, once 12 noon hits, the website continues to show AM until 1:00 then it switches over to PM.
 - I just am not sure what I would need to change in the .js to fix this myself, so figured I would reach out and see what you think.

Thanks!

**Comment by Ozencb** [comment]
Thank you for reporting the bug. It seems to be working now.

**Comment by ozencb** [comment]
Thank you for reporting the bug. It seems to be working properly now.

**Comment by travisjneuman** [comment]
Not a problem.

Awesome! I missed the time frame today, but I will keep an eye on it tonight/tomorrow and report back if I see anything else.

Thanks again @Ozencb!

**Comment by ozencb** [comment]
Great! If you want to reproduce the bug at once you can simply change your OS time settings and that should do it.

**Comment by travisjneuman** [comment]
Good Point. Just put this same fix into my site, and seems to be all set after I just tested! Thanks again.
