### ISSUE TITLE
Influencer based on commands Names

### ISSUE THREAD

**Issue by anandcu3** [Ozencb/tilde-enhanced#6]
This will enable suggestions based on command names and makes it easier to launch commands with similar keys. This should be quite easy to do since all the required data is right there, but I'm a newbie in js. Any suggestions on how to add this?

**Comment by ozencb** [comment]
Hello, sorry for the late reply. I am not sure if I get your request right, can you provide an example? what should the new functionality be and what the expected results are?

**Comment by anandcu3** [comment]
Here's an example. I have three links, discord, google drive, google docs. Now I cant use the key  "d" as a shortcut for all of them. So when I type "d", the search suggestion can show me drive, discord, docs (from google) etc. Which come from the name field in the commands list in the file `script.js`  Hope its more clear now.

**Comment by xvvvyz** [comment]
@anandcu3 @Ozencb, if I'm understanding this correctly, I think you could get away with using the `Default` influencer here.. e.g

```javascript
{
  commands: [
    {
      key: 'Discord',
      // ...
    },
    {
      key: 'Drive',
      // ...
    },
    {
      key: 'Docs',
      // ...
    },
  ],
  defaultSuggestions: {
    d: ['Discord', 'Drive', 'Docs'],
  },
}
```

**Comment by ozencb** [comment]
Hello, @cadejscroggins. I couldn't thank you personally before for creating Tilde. I probably wouldn't be able to build it myself from the ground up, so thank you! ☺

Anyways, if @anandcu3 's case only involves the "d" key, `defaultSuggestions` should be more than enough. But that wouldn't be dynamic, obviously, so the user would have to find and fix these edge cases manually by adding every shortcut to `defaultSuggestions`. 

@anandcu3 Is Cade's approach enough for you or do you need something dynamic?

**Comment by anandcu3** [comment]
@Ozencb `DefaultSuggestions` works as a good alternative., I've tried setting it up. But it requires a lot of manual effort. The dynamic approach to get them from command keys would be a better way to do it.

**Comment by ozencb** [comment]
Feature added
2ad4f517c968c7b3b1c940e060d956d9a53764aa

**Comment by ozencb** [comment]
@anandcu3 Can you test and confirm that new Influencer is working fine for you?

**Comment by anandcu3** [comment]
Yes working great! Thanks @Ozencb
