### ISSUE TITLE
Using Svgs

### ISSUE THREAD

**Issue by varlevi** [Ozencb/tilde-enhanced#7]
Hi! I LOVE this project. It fits in perfectly with my setup and is so simple to use, so thank you for that! However, I have noticed one (small) project. The project only lets me use pngs for the icons, where I want to be able to use svgs. Is there a way to do this already? And if not, is it something that could be added? Thanks!

**Comment by ozencb** [comment]
I will look into it 👍

**Comment by ozencb** [comment]
Feature added in e732b3eccf32cb4f27ab170c721660e0c2f1c80b
