### ISSUE TITLE
How can you get rid of all the icons?

### ISSUE THREAD

**Issue by aravind987** [Ozencb/tilde-enhanced#9]
Loving this startpage so far, but I'd like to get rid of all the icons. I often add and remove links from the startpage and for some lesser-known pages it is a real pain to try and find good icons as I do not have the time to create my own. But to be honest, I'd be fine without the icons, so how would I go about removing the icons? I tried commenting out the icon line for each element in config.js but that just replaces it with a placeholder.

**Comment by ozencb** [comment]
Try typing in 'keys!'

**Comment by aravind987** [comment]
Where do I type that in? I tried that in config.js so my entry looked like this: 

category: 'General',
      name: 'Personal Email',
      key: 'm',
      url: 'https://gmail.com',
      search: '/#search/text={}',
      color: 'linear-gradient(135deg, #dd5145, #dd5145)',
      icon: 'keys!',
      quickLaunch: true,

This also just replaces the icon with the placeholder

**Comment by ozencb** [comment]
Not in the config file, directly in the page. It is a command that replaces icons with whatever letters you have in `key` attribute, in your example's case the letter 'm'.

**Comment by aravind987** [comment]
Oh okay that works great thanks!

**Comment by ozencb** [comment]
Great! I am closing the issue then.
